childrenForm:
  custBinDir_1: /home/pi/Documents/Espressif/esptool_ui/data/oralb_turing_seagate_v0.2.5-1.bin
  custBinDir_2: ''
  custBinDir_3: ''
  custBinDir_4: ''
  custBinOffset_1: ''
  custBinOffset_2: ''
  custBinOffset_3: ''
  custBinOffset_4: ''
  pieBinDir_1: ''
  pieBinDir_2: ''
  pieBinDir_3: ''
  pieBinDir_4: ''
  pieBinOffset_1: ''
  pieBinOffset_2: ''
  pieBinOffset_3: ''
  pieBinOffset_4: ''
mainForm:
  custFwEdit: /home/pi/Documents/Espressif/esptool_ui/data/50FW-000X0-P1C-0200-121_0x6000AD52.bin
  pieFwEdit: ''
