# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/wyx/Documents/pi/DC5270/Esp32DownloadTools/PyQTUI/childrenForm.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(548, 584)
        Form.setMinimumSize(QtCore.QSize(548, 362))
        Form.setMaximumSize(QtCore.QSize(548, 700))
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 230, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 390, 151, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(470, 230, 41, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(470, 390, 41, 16))
        self.label_4.setObjectName("label_4")
        self.binFileComfirm = QtWidgets.QDialogButtonBox(Form)
        self.binFileComfirm.setGeometry(QtCore.QRect(130, 550, 251, 26))
        self.binFileComfirm.setStandardButtons(QtWidgets.QDialogButtonBox.Discard|QtWidgets.QDialogButtonBox.Save)
        self.binFileComfirm.setCenterButtons(True)
        self.binFileComfirm.setObjectName("binFileComfirm")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 410, 521, 122))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.custBinDir_1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.custBinDir_1.setObjectName("custBinDir_1")
        self.verticalLayout.addWidget(self.custBinDir_1)
        self.custBinDir_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.custBinDir_2.setMinimumSize(QtCore.QSize(390, 0))
        self.custBinDir_2.setObjectName("custBinDir_2")
        self.verticalLayout.addWidget(self.custBinDir_2)
        self.custBinDir_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.custBinDir_3.setObjectName("custBinDir_3")
        self.verticalLayout.addWidget(self.custBinDir_3)
        self.custBinDir_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.custBinDir_4.setObjectName("custBinDir_4")
        self.verticalLayout.addWidget(self.custBinDir_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.custBinOptBtn_1 = QtWidgets.QToolButton(self.layoutWidget)
        self.custBinOptBtn_1.setObjectName("custBinOptBtn_1")
        self.verticalLayout_3.addWidget(self.custBinOptBtn_1)
        self.custBinOptBtn_2 = QtWidgets.QToolButton(self.layoutWidget)
        self.custBinOptBtn_2.setObjectName("custBinOptBtn_2")
        self.verticalLayout_3.addWidget(self.custBinOptBtn_2)
        self.custBinOptBtn_3 = QtWidgets.QToolButton(self.layoutWidget)
        self.custBinOptBtn_3.setObjectName("custBinOptBtn_3")
        self.verticalLayout_3.addWidget(self.custBinOptBtn_3)
        self.custBinOptBtn_4 = QtWidgets.QToolButton(self.layoutWidget)
        self.custBinOptBtn_4.setObjectName("custBinOptBtn_4")
        self.verticalLayout_3.addWidget(self.custBinOptBtn_4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.custBinOffset_1 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.custBinOffset_1.sizePolicy().hasHeightForWidth())
        self.custBinOffset_1.setSizePolicy(sizePolicy)
        self.custBinOffset_1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.custBinOffset_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.custBinOffset_1.setText("")
        self.custBinOffset_1.setObjectName("custBinOffset_1")
        self.verticalLayout_2.addWidget(self.custBinOffset_1)
        self.custBinOffset_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.custBinOffset_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.custBinOffset_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.custBinOffset_2.setObjectName("custBinOffset_2")
        self.verticalLayout_2.addWidget(self.custBinOffset_2)
        self.custBinOffset_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.custBinOffset_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.custBinOffset_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.custBinOffset_3.setObjectName("custBinOffset_3")
        self.verticalLayout_2.addWidget(self.custBinOffset_3)
        self.custBinOffset_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.custBinOffset_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.custBinOffset_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.custBinOffset_4.setObjectName("custBinOffset_4")
        self.verticalLayout_2.addWidget(self.custBinOffset_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 250, 521, 124))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pieBinDir_1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pieBinDir_1.setObjectName("pieBinDir_1")
        self.verticalLayout_7.addWidget(self.pieBinDir_1)
        self.pieBinDir_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pieBinDir_2.setMinimumSize(QtCore.QSize(390, 0))
        self.pieBinDir_2.setObjectName("pieBinDir_2")
        self.verticalLayout_7.addWidget(self.pieBinDir_2)
        self.pieBinDir_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pieBinDir_3.setObjectName("pieBinDir_3")
        self.verticalLayout_7.addWidget(self.pieBinDir_3)
        self.pieBinDir_4 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pieBinDir_4.setObjectName("pieBinDir_4")
        self.verticalLayout_7.addWidget(self.pieBinDir_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pieBinOptBtn_1 = QtWidgets.QToolButton(self.layoutWidget1)
        self.pieBinOptBtn_1.setObjectName("pieBinOptBtn_1")
        self.verticalLayout_8.addWidget(self.pieBinOptBtn_1)
        self.pieBinOptBtn_2 = QtWidgets.QToolButton(self.layoutWidget1)
        self.pieBinOptBtn_2.setObjectName("pieBinOptBtn_2")
        self.verticalLayout_8.addWidget(self.pieBinOptBtn_2)
        self.pieBinOptBtn_3 = QtWidgets.QToolButton(self.layoutWidget1)
        self.pieBinOptBtn_3.setObjectName("pieBinOptBtn_3")
        self.verticalLayout_8.addWidget(self.pieBinOptBtn_3)
        self.pieBinOptBtn_4 = QtWidgets.QToolButton(self.layoutWidget1)
        self.pieBinOptBtn_4.setObjectName("pieBinOptBtn_4")
        self.verticalLayout_8.addWidget(self.pieBinOptBtn_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pieBinOffset_1 = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pieBinOffset_1.sizePolicy().hasHeightForWidth())
        self.pieBinOffset_1.setSizePolicy(sizePolicy)
        self.pieBinOffset_1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pieBinOffset_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pieBinOffset_1.setObjectName("pieBinOffset_1")
        self.verticalLayout_9.addWidget(self.pieBinOffset_1)
        self.pieBinOffset_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pieBinOffset_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pieBinOffset_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pieBinOffset_2.setObjectName("pieBinOffset_2")
        self.verticalLayout_9.addWidget(self.pieBinOffset_2)
        self.pieBinOffset_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pieBinOffset_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pieBinOffset_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pieBinOffset_3.setObjectName("pieBinOffset_3")
        self.verticalLayout_9.addWidget(self.pieBinOffset_3)
        self.pieBinOffset_4 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pieBinOffset_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pieBinOffset_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pieBinOffset_4.setObjectName("pieBinOffset_4")
        self.verticalLayout_9.addWidget(self.pieBinOffset_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 10, 511, 60))
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pieBinDir_5 = QtWidgets.QLineEdit(self.widget)
        self.pieBinDir_5.setObjectName("pieBinDir_5")
        self.horizontalLayout_4.addWidget(self.pieBinDir_5)
        self.pieBinOptBtn_5 = QtWidgets.QToolButton(self.widget)
        self.pieBinOptBtn_5.setObjectName("pieBinOptBtn_5")
        self.horizontalLayout_4.addWidget(self.pieBinOptBtn_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pieBinDir_6 = QtWidgets.QLineEdit(self.widget)
        self.pieBinDir_6.setObjectName("pieBinDir_6")
        self.horizontalLayout_5.addWidget(self.pieBinDir_6)
        self.pieBinOptBtn_6 = QtWidgets.QToolButton(self.widget)
        self.pieBinOptBtn_6.setObjectName("pieBinOptBtn_6")
        self.horizontalLayout_5.addWidget(self.pieBinOptBtn_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.custBinDir_1, self.custBinOptBtn_1)
        Form.setTabOrder(self.custBinOptBtn_1, self.custBinOffset_1)
        Form.setTabOrder(self.custBinOffset_1, self.custBinDir_2)
        Form.setTabOrder(self.custBinDir_2, self.custBinOptBtn_2)
        Form.setTabOrder(self.custBinOptBtn_2, self.custBinOffset_2)
        Form.setTabOrder(self.custBinOffset_2, self.custBinDir_3)
        Form.setTabOrder(self.custBinDir_3, self.custBinOptBtn_3)
        Form.setTabOrder(self.custBinOptBtn_3, self.custBinOffset_3)
        Form.setTabOrder(self.custBinOffset_3, self.custBinDir_4)
        Form.setTabOrder(self.custBinDir_4, self.custBinOptBtn_4)
        Form.setTabOrder(self.custBinOptBtn_4, self.custBinOffset_4)
        Form.setTabOrder(self.custBinOffset_4, self.pieBinDir_1)
        Form.setTabOrder(self.pieBinDir_1, self.pieBinOptBtn_1)
        Form.setTabOrder(self.pieBinOptBtn_1, self.pieBinOffset_1)
        Form.setTabOrder(self.pieBinOffset_1, self.pieBinDir_2)
        Form.setTabOrder(self.pieBinDir_2, self.pieBinOptBtn_2)
        Form.setTabOrder(self.pieBinOptBtn_2, self.pieBinOffset_2)
        Form.setTabOrder(self.pieBinOffset_2, self.pieBinDir_3)
        Form.setTabOrder(self.pieBinDir_3, self.pieBinOptBtn_3)
        Form.setTabOrder(self.pieBinOptBtn_3, self.pieBinOffset_3)
        Form.setTabOrder(self.pieBinOffset_3, self.pieBinDir_4)
        Form.setTabOrder(self.pieBinDir_4, self.pieBinOptBtn_4)
        Form.setTabOrder(self.pieBinOptBtn_4, self.pieBinOffset_4)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Origin Bin Firmware Setting"))
        self.label_2.setText(_translate("Form", "Tester bin file dir"))
        self.label.setText(_translate("Form", "Customer bin file dir"))
        self.label_3.setText(_translate("Form", "offset"))
        self.label_4.setText(_translate("Form", "offset"))
        self.custBinOptBtn_1.setText(_translate("Form", "..."))
        self.custBinOptBtn_2.setText(_translate("Form", "..."))
        self.custBinOptBtn_3.setText(_translate("Form", "..."))
        self.custBinOptBtn_4.setText(_translate("Form", "..."))
        self.pieBinOptBtn_1.setText(_translate("Form", "..."))
        self.pieBinOptBtn_2.setText(_translate("Form", "..."))
        self.pieBinOptBtn_3.setText(_translate("Form", "..."))
        self.pieBinOptBtn_4.setText(_translate("Form", "..."))
        self.label_5.setText(_translate("Form", "Tester zip dir"))
        self.label_6.setText(_translate("Form", "Customer zip dir"))
        self.pieBinOptBtn_5.setText(_translate("Form", "..."))
        self.pieBinOptBtn_6.setText(_translate("Form", "..."))
