# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/wyx/Documents/pi/DC5270/Esp32DownloadTools/PyQTUI/childrenForm.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(548, 550)
        Form.setMinimumSize(QtCore.QSize(548, 362))
        Form.setMaximumSize(QtCore.QSize(548, 550))
        self.binFileComfirm = QtWidgets.QDialogButtonBox(Form)
        self.binFileComfirm.setGeometry(QtCore.QRect(130, 510, 251, 26))
        self.binFileComfirm.setStandardButtons(QtWidgets.QDialogButtonBox.Discard|QtWidgets.QDialogButtonBox.Save)
        self.binFileComfirm.setCenterButtons(True)
        self.binFileComfirm.setObjectName("binFileComfirm")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 481, 64))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tester_zip_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.tester_zip_edit.setObjectName("tester_zip_edit")
        self.horizontalLayout_4.addWidget(self.tester_zip_edit)
        self.tester_zip_btn = QtWidgets.QToolButton(self.layoutWidget)
        self.tester_zip_btn.setObjectName("tester_zip_btn")
        self.horizontalLayout_4.addWidget(self.tester_zip_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cust_zip_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.cust_zip_edit.setObjectName("cust_zip_edit")
        self.horizontalLayout_5.addWidget(self.cust_zip_edit)
        self.cust_zip_btn = QtWidgets.QToolButton(self.layoutWidget)
        self.cust_zip_btn.setObjectName("cust_zip_btn")
        self.horizontalLayout_5.addWidget(self.cust_zip_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(0, 80, 541, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(0, 290, 541, 20))
        self.label_10.setObjectName("label_10")
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 100, 496, 188))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setMinimumSize(QtCore.QSize(210, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pieFwEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pieFwEdit.setObjectName("pieFwEdit")
        self.horizontalLayout_7.addWidget(self.pieFwEdit)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pieBinDir_1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pieBinDir_1.setObjectName("pieBinDir_1")
        self.verticalLayout_7.addWidget(self.pieBinDir_1)
        self.pieBinDir_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pieBinDir_2.setMinimumSize(QtCore.QSize(390, 0))
        self.pieBinDir_2.setObjectName("pieBinDir_2")
        self.verticalLayout_7.addWidget(self.pieBinDir_2)
        self.pieBinDir_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pieBinDir_3.setObjectName("pieBinDir_3")
        self.verticalLayout_7.addWidget(self.pieBinDir_3)
        self.pieBinDir_4 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pieBinDir_4.setObjectName("pieBinDir_4")
        self.verticalLayout_7.addWidget(self.pieBinDir_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pieBinOffset_1 = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pieBinOffset_1.sizePolicy().hasHeightForWidth())
        self.pieBinOffset_1.setSizePolicy(sizePolicy)
        self.pieBinOffset_1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pieBinOffset_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pieBinOffset_1.setObjectName("pieBinOffset_1")
        self.verticalLayout_9.addWidget(self.pieBinOffset_1)
        self.pieBinOffset_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pieBinOffset_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pieBinOffset_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pieBinOffset_2.setObjectName("pieBinOffset_2")
        self.verticalLayout_9.addWidget(self.pieBinOffset_2)
        self.pieBinOffset_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pieBinOffset_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pieBinOffset_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pieBinOffset_3.setObjectName("pieBinOffset_3")
        self.verticalLayout_9.addWidget(self.pieBinOffset_3)
        self.pieBinOffset_4 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pieBinOffset_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pieBinOffset_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pieBinOffset_4.setObjectName("pieBinOffset_4")
        self.verticalLayout_9.addWidget(self.pieBinOffset_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_11)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 310, 494, 184))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setMinimumSize(QtCore.QSize(210, 0))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.custFwEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.custFwEdit.setObjectName("custFwEdit")
        self.horizontalLayout_8.addWidget(self.custFwEdit)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.custBinDir_1 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.custBinDir_1.setObjectName("custBinDir_1")
        self.verticalLayout.addWidget(self.custBinDir_1)
        self.custBinDir_2 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.custBinDir_2.setMinimumSize(QtCore.QSize(390, 0))
        self.custBinDir_2.setObjectName("custBinDir_2")
        self.verticalLayout.addWidget(self.custBinDir_2)
        self.custBinDir_3 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.custBinDir_3.setObjectName("custBinDir_3")
        self.verticalLayout.addWidget(self.custBinDir_3)
        self.custBinDir_4 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.custBinDir_4.setObjectName("custBinDir_4")
        self.verticalLayout.addWidget(self.custBinDir_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.custBinOffset_1 = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.custBinOffset_1.sizePolicy().hasHeightForWidth())
        self.custBinOffset_1.setSizePolicy(sizePolicy)
        self.custBinOffset_1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.custBinOffset_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.custBinOffset_1.setText("")
        self.custBinOffset_1.setObjectName("custBinOffset_1")
        self.verticalLayout_2.addWidget(self.custBinOffset_1)
        self.custBinOffset_2 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.custBinOffset_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.custBinOffset_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.custBinOffset_2.setObjectName("custBinOffset_2")
        self.verticalLayout_2.addWidget(self.custBinOffset_2)
        self.custBinOffset_3 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.custBinOffset_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.custBinOffset_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.custBinOffset_3.setObjectName("custBinOffset_3")
        self.verticalLayout_2.addWidget(self.custBinOffset_3)
        self.custBinOffset_4 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.custBinOffset_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.custBinOffset_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.custBinOffset_4.setObjectName("custBinOffset_4")
        self.verticalLayout_2.addWidget(self.custBinOffset_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout)
        self.verticalLayout_10.addLayout(self.verticalLayout_12)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.custBinDir_1, self.custBinOffset_1)
        Form.setTabOrder(self.custBinOffset_1, self.custBinDir_2)
        Form.setTabOrder(self.custBinDir_2, self.custBinOffset_2)
        Form.setTabOrder(self.custBinOffset_2, self.custBinDir_3)
        Form.setTabOrder(self.custBinDir_3, self.custBinOffset_3)
        Form.setTabOrder(self.custBinOffset_3, self.custBinDir_4)
        Form.setTabOrder(self.custBinDir_4, self.custBinOffset_4)
        Form.setTabOrder(self.custBinOffset_4, self.pieBinDir_1)
        Form.setTabOrder(self.pieBinDir_1, self.pieBinOffset_1)
        Form.setTabOrder(self.pieBinOffset_1, self.pieBinDir_2)
        Form.setTabOrder(self.pieBinDir_2, self.pieBinOffset_2)
        Form.setTabOrder(self.pieBinOffset_2, self.pieBinDir_3)
        Form.setTabOrder(self.pieBinDir_3, self.pieBinOffset_3)
        Form.setTabOrder(self.pieBinOffset_3, self.pieBinDir_4)
        Form.setTabOrder(self.pieBinDir_4, self.pieBinOffset_4)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Settings"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Tester Zip Path</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Customer Zip Path</span></p></body></html>"))
        self.tester_zip_btn.setText(_translate("Form", "..."))
        self.cust_zip_btn.setText(_translate("Form", "..."))
        self.label_9.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#2e3436;\">---------------------------------------------------------------------------------------------------------------------------------------</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#2e3436;\">---------------------------------------------------------------------------------------------------------------------------------------</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "Tester Flash Firmware Path"))
        self.label_2.setText(_translate("Form", "Tester Origin Bin Path"))
        self.label_3.setText(_translate("Form", "Offset"))
        self.label_8.setText(_translate("Form", "Customer Flash Firmware Path"))
        self.label.setText(_translate("Form", "Customer Origin Bin Path"))
        self.label_4.setText(_translate("Form", "Offset"))
